services:
  registry-ui:
    image: joxit/docker-registry-ui:main
    restart: always
    ports:
      - 80:80
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://registry-server:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=true
      - CATALOG_ELEMENTS_LIMIT=1000
    container_name: registry-ui
    depends_on:
      - registry-server

  registry-server:
    image: registry:3.0.0
    restart: unless-stopped
    volumes:
      - ./registry/data:/var/lib/registry
      - ./registry-config/credential.yaml:/etc/docker/registry/config.yml
      - ./registry-config/httpasswd:/etc/docker/registry/htpasswd
    container_name: registry-server
    command: serve /etc/docker/registry/config.yml